CREATE TABLE usuario (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE lista (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Date DATE NOT NULL,
    IsFinished BOOLEAN NOT NULL DEFAULT 0,
    UsuarioID INT,
    FOREIGN KEY (UsuarioID) REFERENCES usuario(ID) ON DELETE CASCADE
);
